{% set data = load_setup_py_data() %}

package:
    name: AItomotools
    # If this release is tagged, use bare version number. Otherwise,
    # append 'dev' to version number.
    # This scheme complies with PEP-386:
    # https://www.python.org/dev/peps/pep-0386/
    {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}
    version: {{ data['version'] }}
    {% else %}
    version: {{ data['version'] + "dev" }}
    {% endif %}

source:
    git_url: ../

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    noarch: python

equirements:
    host:
        - python >=3.6
        - astra-toolbox >=2.0
        - setuptools
        - pytest-runner
        - pytorch

    run:
        - python >=3.6
        - astra-toolbox >=2.0

# about:
#     home: -
#     license: BSD-3
#     license_file: LICENSE
#     summary: ""

# extra:
#     maintainers:
#         - Ander Biguri
